//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Music.Cover.Finder {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Music.Cover.Finder.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover Finder Application, using Discogs API, made with Neutronium.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        internal static string Album {
            get {
                return ResourceManager.GetString("Album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        internal static string Artist {
            get {
                return ResourceManager.GetString("Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to button..
        /// </summary>
        internal static string Button {
            get {
                return ResourceManager.GetString("Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation needed.
        /// </summary>
        internal static string ConfirmationNeeded {
            get {
                return ResourceManager.GetString("ConfirmationNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to https://www.discogs.com/settings/developers. Create an account and generate a token using &apos;Generate new token&apos; button..
        /// </summary>
        internal static string DiscogsExplanation {
            get {
                return ResourceManager.GetString("DiscogsExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to close application?.
        /// </summary>
        internal static string DoYouWantToCloseApplication {
            get {
                return ResourceManager.GetString("DoYouWantToCloseApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to restart application?.
        /// </summary>
        internal static string DoYouWantToRestartApplication {
            get {
                return ResourceManager.GetString("DoYouWantToRestartApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a Discogs Token to start using Music Cover Finder.
        /// </summary>
        internal static string FirstTimeTokenMessage {
            get {
                return ResourceManager.GetString("FirstTimeTokenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to generate a token using.
        /// </summary>
        internal static string GenerateTokenUsing {
            get {
                return ResourceManager.GetString("GenerateTokenUsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to .
        /// </summary>
        internal static string GoTo {
            get {
                return ResourceManager.GetString("GoTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to get a Discogs Token.
        /// </summary>
        internal static string HowToDiscogsToken {
            get {
                return ResourceManager.GetString("HowToDiscogsToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to made by.
        /// </summary>
        internal static string MadeBy {
            get {
                return ResourceManager.GetString("MadeBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string Menu_about {
            get {
                return ResourceManager.GetString("Menu_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        internal static string Menu_authentication {
            get {
                return ResourceManager.GetString("Menu_authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Menu_search {
            get {
                return ResourceManager.GetString("Menu_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid Discogs Token.
        /// </summary>
        internal static string NeedToken {
            get {
                return ResourceManager.GetString("NeedToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No result found.
        /// </summary>
        internal static string NoResultFound {
            get {
                return ResourceManager.GetString("NoResultFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation not available.
        /// </summary>
        internal static string OperationNotAvailable {
            get {
                return ResourceManager.GetString("OperationNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover Finder Application.
        /// </summary>
        internal static string ProjectDescription {
            get {
                return ResourceManager.GetString("ProjectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        internal static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to result found.
        /// </summary>
        internal static string ResultFound {
            get {
                return ResourceManager.GetString("ResultFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to results found.
        /// </summary>
        internal static string ResultsFound {
            get {
                return ResourceManager.GetString("ResultsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To Music Cover Search.
        /// </summary>
        internal static string SearchMusicCover {
            get {
                return ResourceManager.GetString("SearchMusicCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then go to .
        /// </summary>
        internal static string ThenGoTo {
            get {
                return ResourceManager.GetString("ThenGoTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to create a user..
        /// </summary>
        internal static string ToCreateUse {
            get {
                return ResourceManager.GetString("ToCreateUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Discogs.
        /// </summary>
        internal static string VisitDiscogs {
            get {
                return ResourceManager.GetString("VisitDiscogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome To Music Cover Finder.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
    }
}
